const { GoogleGenAI } = require("@google/genai");
const puppeteer = require("puppeteer");
const z = require("zod");
const pdfParse = require("pdf-parse");
const {zodToJsonSchema} = require("zod-to-json-schema")

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const interviewReportSchema = {
  type: "object",
  properties: {
    matchScore: {
      type: "number",
      description: "Match score between 0–100 indicating how well the candidate fits the job",
    },
    technicalQuestions: {
      type: "array",
      items: {
        type: "object",
        properties: {
          question: { type: "string" },
          intention: { type: "string" },
          answer: { type: "string" },
        },
        required: ["question", "intention", "answer"],
      },
    },
    behavioralQuestions: {
      type: "array",
      items: {
        type: "object",
        properties: {
          question: { type: "string" },
          intention: { type: "string" },
          answer: { type: "string" },
        },
        required: ["question", "intention", "answer"],
      },
    },
    skillGaps: {
      type: "array",
      items: {
        type: "object",
        properties: {
          skill: { type: "string" },
          severity: { type: "string", enum: ["low", "medium", "high"] },
        },
        required: ["skill", "severity"],
      },
    },
    preparationPlan: {
      type: "array",
      items: {
        type: "object",
        properties: {
          day: { type: "number" },
          focus: { type: "string" },
          tasks: { type: "array", items: { type: "string" } },
        },
        required: ["day", "focus", "tasks"],
      },
    },
  },
  required: ["matchScore", "technicalQuestions", "behavioralQuestions", "skillGaps", "preparationPlan"],
};

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
  const prompt = `Generate an interview report for a candidate with the following details:
  Resume: ${resume}
  Self Description: ${selfDescription}
  Job Description: ${jobDescription}`;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",   // ✅ Better free tier
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: interviewReportSchema,  // ✅ Plain object, no zod wrapper
      },
    });

    const text = response.text;

    if (!text) throw new Error("Empty response from Gemini");

    console.log("Raw Response:", text);
    return JSON.parse(text);

  } catch (err) {
    console.error("Gemini Error:", err.message);
    throw err;
  }
}


async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" });
    const pdfBuffer = await page.pdf({ format: "A4" });
    await browser.close();
    return pdfBuffer;
}

async function generateResumePdf({resume,selfDescription,jobDescription}){
  const resumePdfSchema=z.object({
    html:z.string().describe("The resume in html format which can be converted to pdf")
  })

  const prompt = `Generate a resume for a candidate with the following details:
Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}
The resume should be in html format and should be well formatted in single page and no text leakage and can be easily converted to pdf.
the reponse should be in json object with a single  field"html" which contains the resume in html format.
the content of resume should not sound like its generated by ai and should be as close as possible to human written resume.
you can highlight the content using some colors or different font styles but the overall format of resume should be simple and clean.
the content should be ATS friendly and should contain all the relevant information about the candidate's experience, skills and education based on the provided resume,self description and job description.
the resume should not be so length,it should be in one single page long only when converted to pdf.focus on the most important and relevant information about the candidate that can increase the chances of getting selected for the interview.`;

const response=await ai.models.generateContent({
    model:"gemini-2.5-flash",
    contents:prompt,
    config:{
        responseMimeType:"application/json",
        responseSchema:zodToJsonSchema(resumePdfSchema),
    }
  })

  const jsonContent=JSON.parse(response.text)

  const pdfBuffer=await generatePdfFromHtml(jsonContent.html)

  return pdfBuffer

}

module.exports = {generateInterviewReport,generateResumePdf};